version: '3.9'

services:
  postgres:
    image: postgres
    container_name: web
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: dashboard
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
